# Generated by Django 5.2.6 on 2026-09-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_services_seo_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backdrop_resume',
            field=models.ImageField(blank=True, help_text="Faint photo inside the résumé's header card. Portrait, ~800 px wide.", upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backdrop_services',
            field=models.ImageField(blank=True, help_text='Faint photo behind the head of /services/. Portrait, ~800 px wide.', upload_to='profile/'),
        ),
    ]
