# Generated by Django 5.2.6 on 2026-09-22 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_profile_backdrops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='The address: /articles/<slug>/. Latin, lowercase, hyphens — e.g. delay-analysis-methods. Keep it stable once published.', max_length=180, unique=True)),
                ('authors', models.CharField(blank=True, help_text="Everyone who wrote it, in the order the paper lists them, e.g. 'H. Naderirad, A. Author'. Empty for an article written alone.", max_length=300)),
                ('cover', models.ImageField(blank=True, help_text='Shown above the article and as the picture when the link is shared. 1200×630 px reads best.', upload_to='articles/')),
                ('pdf', models.FileField(blank=True, help_text='The full text as a PDF. Offered as a download on the article page.', upload_to='articles/pdf/')),
                ('doi', models.CharField(blank=True, help_text='e.g. 10.1016/j.autcon.2024.105000 — without https://doi.org/.', max_length=120)),
                ('external_url', models.URLField(blank=True, help_text="The article on the publisher's site, Civilica, ResearchGate or LinkedIn.", max_length=500)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The publication date. The list is ordered by it.')),
                ('is_published', models.BooleanField(default=True)),
                ('title_fa', models.CharField(blank=True, max_length=220)),
                ('title_en', models.CharField(blank=True, max_length=220)),
                ('title_de', models.CharField(blank=True, max_length=220)),
                ('abstract_fa', models.TextField(blank=True, help_text='The abstract, or two or three sentences on what the article argues. Shown in the list and at the top of the page; the first ~160 characters are the search result description.')),
                ('abstract_en', models.TextField(blank=True, help_text='The abstract, or two or three sentences on what the article argues. Shown in the list and at the top of the page; the first ~160 characters are the search result description.')),
                ('abstract_de', models.TextField(blank=True, help_text='The abstract, or two or three sentences on what the article argues. Shown in the list and at the top of the page; the first ~160 characters are the search result description.')),
                ('body_fa', models.TextField(blank=True, help_text='Optional for a paper that is published elsewhere — the abstract and the PDF are then the page. Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.')),
                ('body_en', models.TextField(blank=True, help_text='Optional for a paper that is published elsewhere — the abstract and the PDF are then the page. Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.')),
                ('body_de', models.TextField(blank=True, help_text='Optional for a paper that is published elsewhere — the abstract and the PDF are then the page. Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.')),
                ('venue_fa', models.CharField(blank=True, help_text="Where it was published: journal, conference or magazine, e.g. '12th International Conference on Civil Engineering'. Empty for an article written for this site.", max_length=220)),
                ('venue_en', models.CharField(blank=True, help_text="Where it was published: journal, conference or magazine, e.g. '12th International Conference on Civil Engineering'. Empty for an article written for this site.", max_length=220)),
                ('venue_de', models.CharField(blank=True, help_text="Where it was published: journal, conference or magazine, e.g. '12th International Conference on Civil Engineering'. Empty for an article written for this site.", max_length=220)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.tag')),
            ],
            options={
                'ordering': ('-published_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/body/')),
                ('alt', models.CharField(blank=True, help_text='What the image shows, in a few words. Read aloud by screen readers and by Google Images.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.article')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
